// <auto-generated />
using System;
using ArtShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtShop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240225190914_Add-InitialSeed")]
    partial class AddInitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtShop.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Depth")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFramed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<int>("YearMade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StyleId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("ArtShop.Data.Models.ArtworkCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("ArtworksCategories");
                });

            modelBuilder.Entity("ArtShop.Data.Models.ArtworkOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("ArtworksOrders");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArtShop.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bahamas, The"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 45,
                            Name = "China"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 51,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 62,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 63,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 69,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fiji Islands"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 75,
                            Name = "France"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Gambia, The"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 89,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Man, Isle of"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Falkland Islands (Islas Malvinas)"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 112,
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 115,
                            Name = "U.S. Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 120,
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 121,
                            Name = "India"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Macedonia, Former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 175,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 176,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 184,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Saara OcIdental"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 201,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 202,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 209,
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 221,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 224,
                            Name = "SuriName"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Jan Mayen"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 230,
                            Name = "French Southern and Antarctic Lands"
                        },
                        new
                        {
                            Id = 231,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Palestinian Authority"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Democratic Republic of Timor-Leste"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 235,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 236,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 237,
                            Name = "TrinIdad and Tobago"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 239,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 240,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 241,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 243,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 244,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 245,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 246,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 247,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 248,
                            Name = "Bolivarian Republic of Venezuela"
                        },
                        new
                        {
                            Id = 249,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 250,
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 251,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 252,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ArtShop.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtworkId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abstract"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Collage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expressive and Gestural"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Graphic, Typographic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Impressionistic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Photorealistic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Naive"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Surrealistic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Urban and Pop"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Unspecified"
                        });
                });

            modelBuilder.Entity("ArtShop.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abstract and Non-Figurative"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Animals And Birds"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Architecture and Cityscapes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flowers and Plants"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Landscapes, Sea and Sky"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nudes and Erotic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "People and Portraits"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Still Life"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Transportation and Maps"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArtShop.Data.Models.Address", b =>
                {
                    b.HasOne("ArtShop.Data.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Artwork", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtShop.Data.Models.Style", "Style")
                        .WithMany("Artworks")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtShop.Data.Models.Subject", "Subject")
                        .WithMany("Artworks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Style");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ArtShop.Data.Models.ArtworkCategory", b =>
                {
                    b.HasOne("ArtShop.Data.Models.Artwork", "Artwork")
                        .WithMany("ArtworksCategories")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtShop.Data.Models.Category", "Category")
                        .WithMany("ArtworksCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ArtShop.Data.Models.ArtworkOrder", b =>
                {
                    b.HasOne("ArtShop.Data.Models.Artwork", "Artwork")
                        .WithMany("ArtworksOrders")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtShop.Data.Models.Order", "Order")
                        .WithMany("ArtworksOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ArtShop.Data.Models.City", b =>
                {
                    b.HasOne("ArtShop.Data.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Order", b =>
                {
                    b.HasOne("ArtShop.Data.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Review", b =>
                {
                    b.HasOne("ArtShop.Data.Models.Artwork", "Artwork")
                        .WithMany("Reviews")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtShop.Data.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Artwork", b =>
                {
                    b.Navigation("ArtworksCategories");

                    b.Navigation("ArtworksOrders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Category", b =>
                {
                    b.Navigation("ArtworksCategories");
                });

            modelBuilder.Entity("ArtShop.Data.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Order", b =>
                {
                    b.Navigation("ArtworksOrders");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Style", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("ArtShop.Data.Models.Subject", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
